#!/bin/sh

set -e

#do_check_runtestflags --suite gcc bla.exp bla.c

l=$(cd $(dirname $0); pwd)
. ${l}/set_infra
. ${l}/set_site
makeflags="-j${parallel}"
#makeflags="$makeflags -d"

if [ "$1" = "--suite" ]; then
    shift
    suite=$1
    shift
    target=check-${suite}
else
    target=check
fi

cd build 

if [ ! -e gcc/xgcc ]; then
    echo "$(basename $0): error: build does not contain xgcc"
    exit 1;
fi

set -x
make \
  -k \
  ${makeflags} \
  ${target} RUNTESTFLAGS="$*" \
  > CHECKLOG 2>&1
