#!/bin/sh

out=""
while true; do
  if [ $# -eq 0 ]; then
    break
  fi
  arg=$1
  if [ "$arg" = "-o" ]; then
    shift
    out=$1
  fi
  shift
done

if [ "$out" = "" ]; then
  out=a.out
fi

echo dummy > $out
